# Generated by Django 4.0.5 on 2022-06-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_fn', models.TextField(max_length=30)),
                ('author_mi', models.TextField(blank=True, max_length=20)),
                ('author_ln', models.TextField(blank=True, max_length=30)),
                ('title', models.TextField(max_length=100)),
                ('genre', models.TextField(blank=True, choices=[('Fiction', 'Fiction'), ('Nonfiction', 'Nonfiction'), ('Other', 'Other')])),
                ('isbn', models.TextField(blank=True, max_length=15)),
            ],
        ),
    ]
