# Generated by Django 4.0.5 on 2022-07-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_remove_book_author_fn_remove_book_author_ln_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_name',
            new_name='author_fname',
        ),
        migrations.AddField(
            model_name='book',
            name='author_lname',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
